[package]
name = "axum-user"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["examples/askama"]

[dependencies]
axum = "0.7.7"
axum-extra = { version = "0.9.4", features = ["cookie-private"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
anyhow = { version = "1.0.89", optional = true }
chrono = { version = "0.4.38", optional = true }
lettre = { version = "0.11.9", optional = true }
oauth2 = { version = "4.4.2", optional = true }
serde_json = { version = "1.0.128", optional = true }
url = { version = "2.5.2", optional = true }
reqwest = { version = "0.12.8", features = ["json"], optional = true }
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
thiserror = "1.0.64"

[features]
default = ["email", "password", "oauth"]
email = ["dep:chrono", "dep:lettre", "dep:url"]
email-login = []
email-signup = []
email-verify = []
email-reset-password = []
oauth = ["dep:chrono", "dep:oauth2", "dep:url", "dep:anyhow", "dep:serde_json", "dep:reqwest"]
oauth-login = []
oauth-signup = []
oauth-link = []
oauth-refresh = []
password = []
password-login = []
password-signup = []
password-email-reset = []
