[editor]
workspace-lsp-roots = [
  "examples"
  # "examples/email-otp",
  # "examples/full",
  # "examples/memory-store",
  # "examples/multi-tenant",
  # "examples/password-only",
  # "examples/postgres-store",
  # "examples/target",
]
