[editor]
workspace-lsp-roots = [
  "./examples/memory-store-oauth-only",
  "./examples/memory-store",
  "./examples/memory-store-password-only-no-templates",
  "./examples/psql-store",
  "./examples/leptos-basic",
]
