[editor]
workspace-lsp-roots = [
  "examples/leptos-basic",
  "examples/memory-store",
  "examples/memory-store-oauth-only",
  "examples/memory-store-password-only-no-templates",
  "examples/psql-store",
]
