[[language]]
name = "rust"
roots = ["Cargo.toml", "Cargo.lock", "tailwind.config.js"]
language-servers = ["rust-analyzer", { name = "vscode-html-language-server", except-features = ["format"] }, "tailwindcss-ls", "emmet-ls"]

[language-server.rust-analyzer.config]
rustfmt = { overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"], procMacro = { ignored = { leptos_macro = ["server"] } } }
cargo = { features = "all" }

[language-server.tailwindcss-ls]
config = { tailwindCSS = { includeLanguages = { rust = "html", "*.rs" = "html" } } }

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[language-server.vscode-css-language-server]
config = { css = { lint = { unknownAtRules = "ignore" } } }
