version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: userp-psql-store
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: userp-psql-store
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - userp-network

volumes:
  postgres-data:

networks:
  userp-network:
    driver: bridge
